public enum Categories {
    HOUSING, TRANSPORTATION, FOOD, UTILITIES,
    CLOTHING, HEALTH, INSURANCE, HOUSEHOLD,
    PERSONAL, DEBT, RETIREMENT, EDUCATION, SAVINGS,
    GIFTS, ENTERTAINMENT, INCOME, UNKNOWN, WITHDRAW
}
